version: '3.9'
services:
  db:
    image: postgres
    shm_size: 128mb
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: docker
      POSTGRES_DATABASE: alura
      POSTGRES_PASSWORD: alura
      POSTGRES_ROOT_HOST: '%'
      POSTGRES_TCP_PORT: 3309
    ports:
      - 3309:3309
    expose:
      - 3309
    networks:
      - armadillo-postgres-network
networks:
  armadillo-postgres-network:
    driver: bridge