insert into genres (name, age_group) values('KODOMO', 'LIVRE');
insert into genres (name, age_group) values('COMEDIA', 'LIVRE');
insert into genres (name, age_group) values('ESCOLAR', 'LIVRE');
insert into genres (name, age_group) values('SLICE OF LIFE', 'LIVRE');
insert into genres (name, age_group) values('AVENTURA', 'LIVRE');
insert into genres (name, age_group) values('ACAO', 'LIVRE');
insert into genres (name, age_group) values('SUPER PODERES', 'LIVRE');
insert into genres (name, age_group) values('PARODIA', 'LIVRE');
insert into genres (name, age_group) values('FANTASIA', 'LIVRE');
insert into genres (name, age_group) values('SHOUNEN', 'MAIOR_10');
insert into genres (name, age_group) values('SHOUJO', 'MAIOR_10');
insert into genres (name, age_group) values('ROMANCE', 'MAIOR_10');
insert into genres (name, age_group) values('SCI-FI', 'MAIOR_10');
insert into genres (name, age_group) values('DEMONIOS', 'MAIOR_12');
insert into genres (name, age_group) values('HORROR', 'MAIOR_12');
insert into genres (name, age_group) values('SOBRENATURAL', 'MAIOR_12');
insert into genres (name, age_group) values('WEBTOON', 'MAIOR_12');
insert into genres (name, age_group) values('YAOI', 'MAIOR_12');
insert into genres (name, age_group) values('YURI', 'MAIOR_12');
insert into genres (name, age_group) values('JIDAIGEKI', 'MAIOR_14');
insert into genres (name, age_group) values('HISTORICO', 'MAIOR_14');
insert into genres (name, age_group) values('ECCHI', 'MAIOR_16'); 
insert into genres (name, age_group) values('GEKIGA', 'MAIOR_18');
insert into genres (name, age_group) values('SEINEN', 'MAIOR_18');
insert into genres (name, age_group) values('JOSEI', 'MAIOR_18');
